### ISSUE TITLE
Livelihood alignment

### ISSUE THREAD

**Issue by michael-smith-nz** [enspiral/enspiral.com-meta#7]
Looking at the Livelihood page(https://enspiral-dev.myshopify.com/pages/livelihood) I'm only seeing two ventures in one row and then a lot of white space where I'd expect to see three ventures.

I had a quick look in the developer tools and it looks like the `ul` element you're using is padding everything to the left 40px. Once I removed that padding it was fixed.

Here's an image of the problem and the green highlight is the padding from the developer tools.
![enspiral-livelihood](https://user-images.githubusercontent.com/1152577/41296666-55ac574e-6e55-11e8-9c8a-b2c516367e56.png)

**Comment by dazyang** [comment]
Thanks @NotThatSmith for taking the time looking into this! I'm working on it now. Venture's page is still work-in-progress – we will have the latest update up and running by end of this week. 😄

**Comment by dazyang** [comment]
**Style won't carry through to overwrite Material Card's default styling.** @agentlewis Can you have a look at this one quickly please. Thx!

<img width="1440" alt="screenshot 2018-06-13 16 25 56" src="https://user-images.githubusercontent.com/29617204/41330297-bf38edea-6f26-11e8-8de0-c6f84f01ca42.png">

<img width="702" alt="screenshot 2018-06-13 16 27 05" src="https://user-images.githubusercontent.com/29617204/41330285-b38f7004-6f26-11e8-98b1-2f6c78c40473.png">

**Comment by dazyang** [comment]
@NotThatSmith Update: now removed in dev! Will update the changes altogether later on. 
<img width="1440" alt="screenshot 2018-06-13 17 11 12" src="https://user-images.githubusercontent.com/29617204/41331385-e8c1ae12-6f2c-11e8-922f-6ec6922d09fd.png">
