### ISSUE TITLE
media slides on home page confusing

### ISSUE THREAD

**Issue by joshuavial** [enspiral/enspiral.com-meta#9]
It took me a handful of confused seconds to realise that the slide show on the bottom of the home page was for media articles and not ventures. My first reaction was "what, stuff has joined Enspiral!?" - a heading might make that more obvious

**Comment by phillcoxon** [comment]
+1 to this. I was confused too.  Having a title of some kind indicating what the content type is might be an idea.

**Comment by dazyang** [comment]
Great feedback – thanks @joshuavial & @phillcoxon ! I will put the title back on, or the title slide back into the carousel.

**Comment by danalexilewis** [comment]
@dazyang I think we could have a small blue banner title like we did on the about page for the faq?

**Comment by dazyang** [comment]
@agentlewis We talked about removing the banner and merging the faq link under Want To Learn more...

**Comment by danalexilewis** [comment]
@dazyang sorry i mean we could use a similar banner on the home page above the slides section

**Comment by dazyang** [comment]
@agentlewis @joshuavial @phillcoxon 
Did a quick fix – what do we think of having a title? The site has also been updated. 
![image](https://user-images.githubusercontent.com/29617204/41330839-db7079b2-6f29-11e8-8e0b-79309c361dbc.png)

**Comment by dazyang** [comment]
@agentlewis oh yes, sorry I replied too quickly to your message. We could do that too.
